#ifndef EXTENSIONS_HPP
#define EXTENSIONS_HPP

#include <string_view>
#include <array>
#include <algorithm>

namespace dirtree {

    inline constexpr std::array text_extensions = {
        std::string_view{".hpp"},
        std::string_view{".as"},
        std::string_view{".asc"},
        std::string_view{".asm"},
        std::string_view{".awk"},
        std::string_view{".bash"},
        std::string_view{".bat"},
        std::string_view{".bib"},
        std::string_view{".c"},
        std::string_view{".c++"},
        std::string_view{".cc"},
        std::string_view{".cfg"},
        std::string_view{".clj"},
        std::string_view{".cmake"},
        std::string_view{".cmd"},
        std::string_view{".conf"},
        std::string_view{".cpp"},
        std::string_view{".cppm"},
        std::string_view{".cs"},
        std::string_view{".css"},
        std::string_view{".csv"},
        std::string_view{".cxx"},
        std::string_view{".d"},
        std::string_view{".dart"},
        std::string_view{".diff"},
        std::string_view{".dockerfile"},
        std::string_view{".el"},
        std::string_view{".elm"},
        std::string_view{".erl"},
        std::string_view{".ex"},
        std::string_view{".exs"},
        std::string_view{".f"},
        std::string_view{".f90"},
        std::string_view{".fish"},
        std::string_view{".fs"},
        std::string_view{".fsi"},
        std::string_view{".fsx"},
        std::string_view{".go"},
        std::string_view{".gradle"},
        std::string_view{".groovy"},
        std::string_view{".h"},
        std::string_view{".h++"},
        std::string_view{".hh"},
        std::string_view{".hpp"},
        std::string_view{".hs"},
        std::string_view{".htm"},
        std::string_view{".html"},
        std::string_view{".hxx"},
        std::string_view{".ini"},
        std::string_view{".inl"},
        std::string_view{".ipp"},
        std::string_view{".ixx"},
        std::string_view{".java"},
        std::string_view{".js"},
        std::string_view{".json"},
        std::string_view{".jsonc"},
        std::string_view{".jsp"},
        std::string_view{".jsx"},
        std::string_view{".kt"},
        std::string_view{".kts"},
        std::string_view{".less"},
        std::string_view{".lisp"},
        std::string_view{".log"},
        std::string_view{".lua"},
        std::string_view{".m"},
        std::string_view{".makefile"},
        std::string_view{".markdown"},
        std::string_view{".md"},
        std::string_view{".mk"},
        std::string_view{".ml"},
        std::string_view{".mli"},
        std::string_view{".mm"},
        std::string_view{".nim"},
        std::string_view{".patch"},
        std::string_view{".php"},
        std::string_view{".pl"},
        std::string_view{".pm"},
        std::string_view{".ps1"},
        std::string_view{".py"},
        std::string_view{".pyi"},
        std::string_view{".pyw"},
        std::string_view{".r"},
        std::string_view{".rb"},
        std::string_view{".rs"},
        std::string_view{".rst"},
        std::string_view{".s"},
        std::string_view{".sass"},
        std::string_view{".scala"},
        std::string_view{".scm"},
        std::string_view{".scss"},
        std::string_view{".sh"},
        std::string_view{".sql"},
        std::string_view{".svg"},
        std::string_view{".swift"},
        std::string_view{".tcl"},
        std::string_view{".tex"},
        std::string_view{".toml"},
        std::string_view{".ts"},
        std::string_view{".tsv"},
        std::string_view{".tsx"},
        std::string_view{".txt"},
        std::string_view{".v"},
        std::string_view{".vb"},
        std::string_view{".vhd"},
        std::string_view{".vhdl"},
        std::string_view{".vim"},
        std::string_view{".vue"},
        std::string_view{".xml"},
        std::string_view{".yaml"},
        std::string_view{".yml"},
        std::string_view{".zig"},
        std::string_view{".zsh"}
    };


    [[nodiscard]] constexpr bool is_text_file(std::string_view ext) noexcept {

        return std::binary_search(text_extensions.begin(), text_extensions.end(), ext);
    }
}

#endif
